name: Delete Old Workflows

on:
  repository_dispatch:
    types: [Remove Old Workflows]
  workflow_dispatch:

env:
  TZ: Asia/Shanghai

jobs:
  cleaning:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Initialization environment
        id: init
        env:
          DEBIAN_FRONTEND: noninteractive
        run: sudo timedatectl set-timezone "$TZ"

      - name: Delete releases and workflows runs
        uses: ophub/delete-releases-workflows@main
        with:
          delete_releases: true
          delete_tags: false
          releases_keep_latest: 5
          delete_workflows: true
          workflows_keep_day: 8
          gh_token: ${{ secrets.GITHUB_TOKEN }}